--liquibase formatted sql

--changeset krupenko:1
create table users
(
    id            bigint generated by default as identity,
    date_of_birth date         not null,
    name          varchar(500) not null,
    password      varchar(500) not null,
    primary key (id)
)

--changeset krupenko:2
create table accounts
(
    id      bigint generated by default as identity,
    user_id bigint  not null unique,
    balance decimal not null,
    primary key (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
)

--changeset krupenko:3
create table email_data
(
    id      bigint generated by default as identity,
    user_id bigint       not null,
    email   varchar(200) not null unique,
    primary key (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
)

--changeset krupenko:4
create table phone_data
(
    id      bigint generated by default as identity,
    user_id bigint      not null,
    phone   varchar(13) not null unique,
    primary key (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
)
